### ISSUE TITLE
Colab not working anymore since last commit

### ISSUE THREAD

**Issue by Mikerhinos** [jantic/DeOldify#181] opened 2020-01-03 18:36 UTC
Hello,

Playing with this awesome tool to colorize old family photos since a couple of days, but today I couldn't get it to work on the colab.
Error when installing requirements.txt : 

_`ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.`_

Before that, I was required to add the clean_mem() function I found on the internet to purge VRAM after each generation too, otherwise I would quickly have the "CUDA out of memory" error.

**Comment by yecs1999** [comment] 2020-01-04 07:27
right before you pip install the requirements.txt, change the last line in requirements.txt from "pillow==6.2.2"
to just
"pillow"
after that it worked okay for me

**Comment by jantic** [comment] 2020-01-04 08:13
Hey guys- sorry- it's fixed now.  I got lazy with the last pull request and neglected to test stuff like I usually do.

**Closed by jantic** 2020-01-04 08:13 UTC

**Comment by Mikerhinos** [comment] 2020-01-04 21:19
Just to confirm that it's working like a charm now, don't even need to add the VRAM purge function anymore too...
Thanks a lot Jason, I feel ashamed that I can't donate anything :(

**Comment by jantic** [comment] 2020-01-06 06:59
Thanks!

**Comment by sachinprabhu007** [comment] 2020-02-12 09:05
Hello 

I tried earlier in January with couple of images, it was working fine, but now it leads to following error

`/usr/local/lib/python3.6/dist-packages/fastai/data_block.py:442: UserWarning: Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.
  warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
/usr/local/lib/python3.6/dist-packages/fastai/data_block.py:445: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  or pass `ignore_empty=True` when labelling to remove this warning.""")
Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /root/.cache/torch/checkpoints/resnet34-333f7ec4.pth
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-22-d41e8163fe4e> in <module>()
----> 1 colorizer = get_image_colorizer(artistic=True)

15 frames
/content/DeOldify/deoldify/visualize.py in get_image_colorizer(render_factor, artistic)
    309 ) -> ModelImageVisualizer:
    310     if artistic:
--> 311         return get_artistic_image_colorizer(render_factor=render_factor)
    312     else:
    313         return get_stable_image_colorizer(render_factor=render_factor)

/content/DeOldify/deoldify/visualize.py in get_artistic_image_colorizer(root_folder, weights_name, results_dir, render_factor)
    332     render_factor: int = 35,
    333 ) -> ModelImageVisualizer:
--> 334     learn = gen_inference_deep(root_folder=root_folder, weights_name=weights_name)
    335     filtr = MasterFilter([ColorizerFilter(learn=learn)], render_factor=render_factor)
    336     vis = ModelImageVisualizer(filtr, results_dir=results_dir)

/content/DeOldify/deoldify/generators.py in gen_inference_deep(root_folder, weights_name, arch, nf_factor)
     85     data = get_dummy_databunch()
     86     learn = gen_learner_deep(
---> 87         data=data, gen_loss=F.l1_loss, arch=arch, nf_factor=nf_factor
     88     )
     89     learn.path = root_folder

/content/DeOldify/deoldify/generators.py in gen_learner_deep(data, gen_loss, arch, nf_factor)
    105         y_range=(-3.0, 3.0),
    106         loss_func=gen_loss,
--> 107         nf_factor=nf_factor,
    108     )
    109 

/content/DeOldify/deoldify/generators.py in unet_learner_deep(data, arch, pretrained, blur_final, norm_type, split_on, blur, self_attention, y_range, last_cross, bottle, nf_factor, **kwargs)
    127     "Build Unet learner from `data` and `arch`."
    128     meta = cnn_config(arch)
--> 129     body = create_body(arch, pretrained)
    130     model = to_device(
    131         DynamicUnetDeep(

/usr/local/lib/python3.6/dist-packages/fastai/vision/learner.py in create_body(arch, pretrained, cut)
     53 def create_body(arch:Callable, pretrained:bool=True, cut:Optional[Union[int, Callable]]=None):
     54     "Cut off the body of a typically pretrained `model` at `cut` (int) or cut the model as specified by `cut(model)` (function)."
---> 55     model = arch(pretrained)
     56     cut = ifnone(cut, cnn_config(arch)['cut'])
     57     if cut is None:

/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py in resnet34(pretrained, progress, **kwargs)
    247     """
    248     return _resnet('resnet34', BasicBlock, [3, 4, 6, 3], pretrained, progress,
--> 249                    **kwargs)
    250 
    251 

/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py in _resnet(arch, block, layers, pretrained, progress, **kwargs)
    221     if pretrained:
    222         state_dict = load_state_dict_from_url(model_urls[arch],
--> 223                                               progress=progress)
    224         model.load_state_dict(state_dict)
    225     return model

/usr/local/lib/python3.6/dist-packages/torch/hub.py in load_state_dict_from_url(url, model_dir, map_location, progress, check_hash)
    490         sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
    491         hash_prefix = HASH_REGEX.search(filename).group(1) if check_hash else None
--> 492         download_url_to_file(url, cached_file, hash_prefix, progress=progress)
    493 
    494     # Note: extractall() defaults to overwrite file if exists. No need to clean up beforehand.

/usr/local/lib/python3.6/dist-packages/torch/hub.py in download_url_to_file(url, dst, hash_prefix, progress)
    389     # We use a different API for python2 since urllib(2) doesn't recognize the CA
    390     # certificates in older Python
--> 391     u = urlopen(url)
    392     meta = u.info()
    393     if hasattr(meta, 'getheaders'):

/usr/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

/usr/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

/usr/lib/python3.6/urllib/request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

/usr/lib/python3.6/urllib/request.py in error(self, proto, *args)
    568         if http_err:
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 
    572 # XXX probably also want an abstract factory that knows when it makes

/usr/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden`


Please assist
Thank you
