### ISSUE TITLE
Tinting towards blue/purple

### ISSUE THREAD

**Issue by karrirasinmaki** [jantic/DeOldify#239] opened 2020-05-21 07:50 UTC
Hey!

First of all, awesome work with the library.

I've been colorizing some old movie clips from the golden swing era and there's one issue commonly seen between clips. The model seems to tint colors towards blue/purple, especially in the case of soldier uniforms. (Seems to be the same issue as reported in #38.)

Attached there are two images of the same frame, one with video model another with artistic model.

![buckprivates-artistic](https://user-images.githubusercontent.com/4706908/82536193-c69ba700-9b50-11ea-8f88-13dfb0e8e969.png)
Original and with the artistic model.

![buckprivates](https://user-images.githubusercontent.com/4706908/82536130-ae2b8c80-9b50-11ea-983b-fa25ef7f49ab.png)
With the video model.

Ps. Another commonly found glitch is the floor tends to have green tinting in it.

**Comment by karrirasinmaki** [comment] 2020-05-21 07:51
I wasn't sure if this was the right place to bring up these issues, but I thought might be useful.

**Comment by jantic** [comment] 2020-05-21 21:41
@karrirasinmaki Oh yeah, this set of color issues is the bane of my existence.  It's slowly getting better with the newer models, but it's a difficult issue. The issue with blue/purple bias really boils down to this: Things like clothing and cars can be pretty much any color, so the model takes a bet on blue/purple because on average they're not bad bets.  It's basically the model cheating the exam. 

I'll keep this open just to let people know it's known, but I can tell you this much:  It'll probably take quite a long time to completely get rid of this problem.

**Comment by karrirasinmaki** [comment] 2020-05-22 07:25
Thank you for the response! The AI is clearly getting clever, learning how to cheat the test.

I wish I'd have the knowledge and skills to help. Best of luck!

**Comment by ysonggit** [comment] 2020-05-22 20:48
Indeed, I find this phenomena as well. A typical example is Audrey Hepburn's cream color dress in Roman Holiday:

|  Original B&W | Colorized |
|---------------|-----------|
|![hepburn_rh](https://user-images.githubusercontent.com/3814842/82707970-740bd900-9c7d-11ea-892d-1383f834d0c2.jpg) | ![hepburn_rh_hd](https://user-images.githubusercontent.com/3814842/82707961-6eae8e80-9c7d-11ea-9ba9-2d3eac211893.jpg) |

The ground truth is:
![il_570xN 1121898953_8uyn](https://user-images.githubusercontent.com/3814842/82707981-7bcb7d80-9c7d-11ea-85a1-5e9f82550248.jpg)

Just bring it up for further optimization.

I can not compliment your work any more, this is a sensational application that will reprint the historical footages of the world!

**Comment by linuxthor** [comment] 2020-06-09 09:22
I have had this issue too and understand why it happens but in this instance I would suggest two things that (in my opinion) can slightly improve the result:

1) Adjust the levels in the source image first
2) Experiment with a range of different 'render factor' settings 

![download (3)](https://user-images.githubusercontent.com/2345732/84129821-5e96fd00-aa3a-11ea-96e2-fa00682bb510.png)

By adjusting the levels first and picking a lower 'render factor' the result is still objectively coloured 'wrong' but I feel like it moves a bit more in the right direction and has a slightly more lifelike feel.

**Comment by theman8631** [comment] 2021-03-10 19:58
With my limited understanding of what's going on besides the explanations of cheating the test I have an assumption and possible suggestion to possibly have some hands on to direct the cheating.

Assumption:  It seems like purple/blue is a frequent guess to cheat the test, but there seems to be multiple guess hues going on, one example is the green floor.  I assume theres a level of certainty going on here, grass and trees are often green, good guess, high certainty.  Color of dress?  Who knows.

Suggestion: is there a way similar to the render factor that we can tweak the hue on the low certainly color choices?  For example if in seeing the playback it looks like purple guesses should be more blue, you could dial the blue in the low certainty purple choices.

I know easier said then done but thought I'd share the brainstorm.  I know it gets farther from an ai model but at some point, unless there's color sources of near same images arn't we going to need some user input?

**Comment by jantic** [comment] 2021-03-11 22:18
@theman8631 I definitely agree with the general idea that the way forward for much better results is to take the strengths of fully automated colorization and marry that with human creativity and intelligence. I think there's a bit of a diminishing returns on fully automated at this point as to how far you can go with that due to the nature of the problem and the limits of current tech. 

That being said I only differ on what I think would be the best way to do this- I think just having the users directly suggest the colors with a dot or scribble on the object would be more intuitive and productive. This is something I plan on exploring pretty soon, but it won't be going into this current project. Rather it'll be in the commercial work for my startup DeOldify.

**Comment by theman8631** [comment] 2021-03-12 00:23
Well sign me up for whatever that software ends up becoming!

**Comment by jantic** [comment] 2021-04-16 00:58
Going to close this.  The problem is acknowledged but there's no plans to improve upon this in this repo.

**Closed by jantic** 2021-04-16 00:58 UTC
